function get2LetterCode(country) {

    let countryCodes = {
        "Albania": 'al',
        "Argentina": 'ar',
        "Australia": 'au',
        "Austria": 'at',
        "Belgium": 'be',
        "Bosnia and Herzegovina": 'ba',
        "Brazil": 'br',
        "Bulgaria": 'bg',
        "Canada": 'ca',
        "Chile": 'cl',
        "Costa Rica": 'cr',
        "Croatia": 'hr',
        "Cyprus": 'cy',
        "Czech Republic": 'cz',
        "Denmark": 'dk',
        "Estonia": 'ee',
        "Finland": 'fi',
        "France": 'fr',
        "Georgia": 'ge',
        "Germany": 'de',
        "Greece": 'gr',
        "Hong Kong": 'hk',
        "Hungary": 'hu',
        "Iceland": 'is',
        "India": 'in',
        "Indonesia": 'id',
        "Ireland": 'ie',
        "Israel": 'il',
        "Italy": 'it',
        "Japan": 'jp',
        "Latvia": 'lv',
        "Luxembourg": 'lu',
        "Malaysia": 'my',
        "Mexico": 'mx',
        "Moldova": 'md',
        "Netherlands": 'nl',
        "New Zealand": 'nz',
        "North Macedonia": 'mk',
        "Norway": 'no',
        "Poland": 'pl',
        "Portugal": 'pt',
        "Romania": 'ro',
        "Serbia": 'rs',
        "Singapore": 'sg',
        "Slovakia": 'sk',
        "Slovenia": 'si',
        "South Africa": 'za',
        "South Korea": 'kr',
        "Spain": 'es',
        "Sweden": 'se',
        "Switzerland": 'ch',
        "Taiwan": 'tw',
        "Thailand": 'th',
        "Turkey": 'tr',
        "Ukraine": 'ua',
        "United Kingdom": 'gb',
        "United States": 'us',
        "Vietnam": 'vn'
    }

    let code = countryCodes[country];
    return code ? code : '';
} 
